# SETUP
DefaultContentLanguage = "en"
baseurl = "https://www.peachepop.com/"
publishdir = "public"
#canonifyUrls = "true"
summaryLength = 15
[outputs]
home = ["HTML", "RSS", "JSON"]
[taxonomies]
category = "categories"
collection = "collections"
eyeliner = "eyeliners"
lash-material = "lash-materials"
lash-type = "lash-types"
tag = "tags"
